[package]
name = "style"
version = "0.1.0"
edition = "2021"

[dependencies]
unit = { path = "../unit" }
document = { path = "../document" }
log = "0.4.17"
colorsys = "0.6.7"
pest = "2.5.5"
pest_derive = "2.5.5"
