[package]
name = "letter"
version = "0.1.0"
edition = "2021"
authors = ["Benjamin Eder <barny.eder@gmail.com>"]
license = "MIT"
description = "Document layout engine"
readme = "README.md"
repository = "https://github.com/bennyboer/letter"

[dependencies]
