[package]
name = "script"
version = "0.1.0"
edition = "2021"

[dependencies]
document = { path = "../document" }
html_parser = { git = "https://github.com/bennyboer/html-parser", branch = "master" }
log = "0.4.17"
